name: funda_demo
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Flutter Material Design Icons
  cupertino_icons: ^1.0.2

  # Network requests library
  dio: ^5.4.3+1

  # State management library
  flutter_bloc: ^8.1.5

  # Environment variables management
  flutter_dotenv: ^5.1.0

  # Logging library
  logger: ^2.2.0

  # JSON serialization library
  json_annotation: ^4.8.1

  # Carousel slider widget
  carousel_slider: ^4.2.1

  # Internationalization and localization library
  intl: ^0.17.0

dev_dependencies:
  # Flutter unit testing library
  flutter_test:
    sdk: flutter

  # Linter for enforcing Flutter best practices
  flutter_lints: ^2.0.0

  # Code generation library for JSON serialization
  build_runner: ^2.4.9

  # JSON serialization support generator
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
